# This file is usually generated by 'nixos-generate-config'
# We provide a template matching the intended ZFS+LUKS layout.

{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Boot Loader and Kernel Configuration
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    # Kernel Modules (from hardware scan + Z16 specifics)
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usb_storage"
        "sd_mod"
        "hid_generic"
        "usbhid"
      ];
      kernelModules = [ "amdgpu" ]; # Early load for KMS
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  # Filesystems (ZFS on LUKS)
  # LUKS device opening is handled in boot.initrd.luks.devices (see core/boot.nix)
  fileSystems = {
    "/" = {
      device = "cake/root";
      fsType = "zfs";
      options = [ "atime=off" ];
    };

    "/nix" = {
      device = "cake/nix";
      fsType = "zfs";
      options = [ "atime=off" ];
    };

    "/var" = {
      device = "cake/var";
      fsType = "zfs";
      options = [ "atime=off" ];
    };

    "/home" = {
      device = "cake/home";
      fsType = "zfs";
      options = [ "atime=off" ];
    };

    "/data" = {
      device = "cake/data";
      fsType = "zfs";
      options = [
        "atime=off"
        "nofail"
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [ { device = "/dev/zvol/cake/swap"; } ];

  # Networking
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
