# This file is usually generated by 'nixos-generate-config'
# We provide a template matching the intended ZFS+LUKS layout.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Boot Loader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Kernel Modules (from hardware scan + Z16 specifics)
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" "hid_generic" "usbhid" ];
  boot.initrd.kernelModules = [ "amdgpu" ]; # Early load for KMS
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Filesystems (ZFS on LUKS)
  # LUKS device opening is handled in boot.initrd.luks.devices (see core/boot.nix)

  fileSystems."/" =
    { device = "cake/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "cake/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "cake/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "cake/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ { device = "/dev/zvol/cake/swap"; } ];

  # Networking
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
