# This file is usually generated by 'nixos-generate-config'
# Tailored for 'petunia' with ZFS on nvme0n1.

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Boot Loader and Kernel Configuration
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    # Pin to 6.12 (LTS) for ZFS stability as per GEMINI.md requirements
    kernelPackages = lib.mkForce pkgs.linuxPackages_6_12;

    # Kernel Modules (from hardware scan + X570 specifics)
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ "nvidia" ]; # Early load for KMS
    };
  };

  # Filesystems (ZFS)
  fileSystems = {
    "/" = {
      device = "petunia/root";
      fsType = "zfs";
    };

    "/nix" = {
      device = "petunia/nix";
      fsType = "zfs";
    };

    "/var" = {
      device = "petunia/var";
      fsType = "zfs";
    };

    "/home" = {
      device = "petunia/home";
      fsType = "zfs";
    };

    "/boot" = {
      # Use GPT partition label, not FAT UUID. mkfs.vfat generates a new random
      # volume serial on every format, so the UUID changes with each reinstall.
      # The GPT partlabel "BOOT" is set by parted and survives every reinstall.
      device = "/dev/disk/by-partlabel/BOOT";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [ { device = "/dev/zvol/petunia/swap"; } ];

  # Networking
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
